### ISSUE TITLE
Error in sap_cast.hpp GCC 4.8.4 locally defined but not used [-Werror=unused-local-typedefs]

### ISSUE THREAD

**Issue by ghost** [synesissoftware/STLSoft-1.9#3]
Ensuring all STLSoft C source files are in UNIX format
g++    -c -Wall -pedantic -Wno-long-long -Wno-unused-value -Wno-unused-function                  -Wno-array-bounds -Werror     -D_REENTRANT -D_DEBUG -UNDEBUG   -Dunix  -DSHWILD_QUALITY_NO_USE_XCOVER  -DPANTHEIOS_NO_AUTO_INIT  -I../../include      -I"/home/ludio/Desktop/stlsoft-1.9.124/include"     -o util.be_parse.mt.debug.o ../../src/util/be.parse.cpp
In file included from /home/ludio/Desktop/stlsoft-1.9.124/include/stlsoft/string/simple_string.hpp:106:0,
                 from /home/ludio/Desktop/stlsoft-1.9.124/include/stlsoft/string/view_slice_functions.hpp:91,
                 from ../../src/util/be.parse.cpp:51:
/home/ludio/Desktop/stlsoft-1.9.124/include/stlsoft/conversion/sap_cast.hpp: In function ‘TO stlsoft::sap_cast(FROM)’:
/home/ludio/Desktop/stlsoft-1.9.124/include/stlsoft/conversion/sap_cast.hpp:145:69: error: typedef ‘from_base_type’ locally defined but not used [-Werror=unused-local-typedefs]
     typedef ss_typename_type_k base_type_traits<FROM>::base_type    from_base_type;
                                                                     ^
/home/ludio/Desktop/stlsoft-1.9.124/include/stlsoft/conversion/sap_cast.hpp:146:69: error: typedef ‘to_base_type’ locally defined but not used [-Werror=unused-local-typedefs]
     typedef ss_typename_type_k base_type_traits<TO>::base_type      to_base_type;
                                                                     ^
cc1plus: all warnings being treated as errors
make: **\* [util.be_parse.mt.debug.o] Error 1

**Comment by mikkoi** [comment]
This is fixed in the version 1.9.125.

**Comment by dansouth** [comment]
I believe this is still present in 1.9.125 (also tried 1.9.126)

```
g++  -D_FILE_OFFSET_BITS=64  -c -Wall -pedantic -Wno-long-long -Wno-unused-value -Wno-unused-function -Werror     -D_REENTRANT -D_DEBUG -UNDEBUG   -Dunix  -DPANTHEIOS_NO_AUTO_INIT  -I../../include -I"<BUILD_DIR>StlSoft/STLSoft-1.9-STLSoft-1.9.125/include"     -o util.be_parse.mt.debug.o ../../src/util/be.parse.cpp
In file included from <BUILD_DIR>StlSoft/STLSoft-1.9-STLSoft-1.9.125/include/stlsoft/string/simple_string.hpp:106:0,
                 from <BUILD_DIR>StlSoft/STLSoft-1.9-STLSoft-1.9.125/include/stlsoft/string/view_slice_functions.hpp:91,
                 from ../../src/util/be.parse.cpp:50:
<BUILD_DIR>StlSoft/STLSoft-1.9-STLSoft-1.9.125/include/stlsoft/conversion/sap_cast.hpp: In function ‘TO stlsoft::sap_cast(FROM)’:
<BUILD_DIR>StlSoft/STLSoft-1.9-STLSoft-1.9.125/include/stlsoft/conversion/sap_cast.hpp:145:69: error: typedef ‘from_base_type’ locally defined but not used [-Werror=unused-local-typedefs]
     typedef ss_typename_type_k base_type_traits<FROM>::base_type    from_base_type;
                                                                     ^
cc1plus: all warnings being treated as errors
```

**Comment by synesissoftware** [comment]
This'll be cleared up in 1.9.132, which should be released within 24 hours
